---
title: "git_00"
author: "Jovy Gomez"
date: "Year 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

Twinkle, Twinkle Little Bat.  
How I wonder what you're at!    
Up above the world you fly,  
Like a tea tray in the sky.  
Twinkle, twinkle, little bat!  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Some say the world will end in fire,  
  Some say in ice.  
  From what I've tasted of desire. 
  I hold with those who favor fire.  
  But if it had to perish twice,  
  I think I know enough of hate. 
  To know that for destruction ice. 
  Is also great. 
  And would suffice.  
 

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,    
Shining with all his might:    
He did his very best to make.  
The billows smooth and bright    
And this was odd, because it was.   
The middle of the night.    

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

When the one whose hand you’re holding.   
Is the one one who holds your heart.   
When the one whose eyes you gaze into.   
Gives your hopes and dreams their start,    
When the one you think of first and last.   
Is the one who holds you tight,    
And the things you plan together.   
Make the whole world seem just right,    
When the one whom you believe in.   
Puts their faith and trust in you,    
You’ve found the one and only love.   
You’ll share your whole life through.    
